language: node_js
node_js:
  - "iojs"
  - "node"
sudo: false
cache:
  directories:
    - node_modules
install:
  - npm install
before_script:
  - npm run lint
script:
  - npm test
before_deploy:
  - npm run build
after_success:
  - npm run publish_coverage
