language: node_js

node_js:
  - 4
  - 6
  - node

cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules

before_install:
  - npm i -g yarn --cache-min 999999999

install:
  - yarn

before_script:
  - yarn lint
  - yarn build

script:
  - yarn test
  - yarn check-coverage

after_success:
  - yarn publish-coverage
